### ISSUE TITLE
Code Ugly

### ISSUE THREAD

**Issue by bagoferasers** [bagoferasers/homeWeatherData#2]
# Tasks:
- [ ] Make code less ugly
- [ ] Remove unnecessary comments.
- [ ] Add proper documentation.
